---CREATED BANK MASTER
CREATE TABLE BANK_MASTER(
NAME VARCHAR(20) PRIMARY KEY,
BALANCE INT CHECK (BALANCE>=5000));

---INSERTED VALUES INTO BANK MASTER
INSERT INTO BANK_MASTER VALUES('PRATIK',10000);
INSERT INTO BANK_MASTER VALUES('SARVESH',20000);
INSERT INTO BANK_MASTER VALUES('VIPUL',100);

SELECT * FROM BANK_MASTER

---CREATED BANK TRANSACTION
CREATE TABLE BANK_TRANSACTION(
NAME VARCHAR(20) FOREIGN KEY REFERENCES BANK_MASTER (NAME),
AMOUNT INT,
TRANS_TYPE CHAR(1) CHECK (TRANS_TYPE='D' OR TRANS_TYPE='W'));

---INSERTED VALUES INTO BANK TRANSACTION
INSERT INTO BANK_TRANSACTION VALUES('SARVESH',2000,'D');
SELECT * FROM BANK_TRANSACTION

ALTER TABLE BANK_TRANSACTION
ADD DATE DATETIME;

UPDATE BANK_TRANSACTION
SET DATE=GETDATE()
WHERE AMOUNT=2000

INSERT INTO BANK_TRANSACTION VALUES('SARVESH',2000,'D',GETDATE());
SELECT * FROM BANK_TRANSACTION
SELECT * FROM BANK_MASTER
