CREATE TABLE MERCHANT (
NAME VARCHAR(20) PRIMARY KEY,
AMOUNT BIGINT);

CREATE TABLE CUSTOMER (
NAME VARCHAR(20) PRIMARY KEY,
AMOUNT BIGINT);

INSERT INTO MERCHANT VALUES('PRATIK',100000);customer

SELECT * FROM MERCHANT

INSERT INTO CUSTOMER VALUES('BEULAH',10000);
INSERT INTO CUSTOMER VALUES('ANKIT',15000);




DELIMITER //
DROP TRIGGER IF EXISTS CHECK_UPDATE_BALANCE //
CREATE TRIGGER CHECK_UPDATE_BALANCE BEFORE UPDATE ON CUSTOMER
FOR EACH ROW
BEGIN
    DECLARE MSG VARCHAR(128);
    IF NEW.AMOUNT < 1000 THEN
        SET MSG = CONCAT('BALANCE ERROR: LOW BALANCE CANNOT UPDATE YOUR BALANCE ', '');
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = MSG;
    END IF;
END
//

DELIMITER ;