ALTER TRIGGER UPDATE_BALANCE
	ON BANK_TRANSACTION
	FOR INSERT 
	AS
	BEGIN TRY
	BEGIN TRANSACTION
		IF((SELECT TRANS_TYPE FROM INSERTED) ='D')
			UPDATE BANK_MASTER
			SET BALANCE = BALANCE +(SELECT AMOUNT FROM INSERTED)
			WHERE BANK_MASTER.NAME=(SELECT NAME FROM INSERTED)
		ELSE
			UPDATE BANK_MASTER
			SET BALANCE = BALANCE -(SELECT AMOUNT FROM INSERTED)
			WHERE BANK_MASTER.NAME=(SELECT NAME FROM INSERTED)
		COMMIT TRANSACTION
	END TRY
	BEGIN CATCH
		ROLLBACK TRANSACTION
	END CATCH
	
INSERT INTO BANK_TRANSACTION VALUES('SARVESH',50000,'A',GETDATE());
SELECT * FROM BANK_TRANSACTION
SELECT * FROM BANK_MASTER
	