/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Pratik_chaurasia' at '7/15/18 6:22 PM' with Gradle 3.0
 *
 * @author Pratik_chaurasia, @date 7/15/18 6:22 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
