/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Pratik_chaurasia' at '7/7/18 11:56 AM' with Gradle 3.0
 *
 * @author Pratik_chaurasia, @date 7/7/18 11:56 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
